version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork

  HelloApi:
    build : ./api
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - mynetwork

  HelloWeb:
    build: ./web
    ports:
      - "8080:8080"
    depends_on:
      - HelloApi
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: musql
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - db-network

volumes:
  mysql-data:

networks:
  db-network:
    driver: bridge
  api-network:
    driver: bridge


